# Generated by Django 4.2 on 2023-04-17 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчества')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_img/')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Эл. почта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профилы',
            },
        ),
    ]
