# Generated by Django 4.2 on 2023-04-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('departure_date', models.DateTimeField(verbose_name='Дата вылета')),
                ('night', models.PositiveIntegerField(default=1, verbose_name='Количество ночей')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
            ],
            options={
                'verbose_name_plural': 'Тур',
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категория туров',
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_img/', verbose_name='Фото')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_image', to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name_plural': 'Тур фото',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_category', to='tour.tourcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_city', to='hotel.city', verbose_name='Город'),
        ),
    ]
