# Generated by Django 4.2 on 2023-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(blank=True, related_name='tour_hotels', to='hotel.hotel', verbose_name='Отели'),
        ),
    ]
