# Generated by Django 4.2 on 2023-04-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0002_alter_point_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(default=0, verbose_name='Балл')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Баллы затраченные',
            },
        ),
        migrations.CreateModel(
            name='PointEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(default=0, verbose_name='Балл')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earned', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Баллы заработанные',
            },
        ),
    ]
