# Generated by Django 4.2 on 2023-04-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_file/')),
                ('point', models.IntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name_plural': 'Задании для полученя баллов',
            },
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='done_task_file/')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверен')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_done', to='task.task', verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Выполненные задании',
            },
        ),
    ]
