# Generated by Django 4.2 on 2023-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdone',
            old_name='title',
            new_name='task',
        ),
    ]
