# Generated by Django 4.2 on 2023-04-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('star_count', models.PositiveIntegerField(default=1, verbose_name='Количества звезд')),
                ('booking_rating', models.FloatField(verbose_name='Рейтинг отеля на Booking')),
                ('tripadvisor_rating', models.FloatField(verbose_name='Рейтинг отеля на Tripadvisor')),
                ('point', models.FloatField(verbose_name='Количество баллов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена за номер')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опмсание на другом сайте')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_city', to='hotel.city', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_img/', verbose_name='Фото')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name_plural': 'Отель Фото',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_region', to='hotel.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_city', to='hotel.country', verbose_name='Страна'),
        ),
    ]
